#!/usr/bin/env bash
set -o errexit
set -o pipefail

main() {
  local name="${1:-gesund}"

  eval "$(tfw printenv gesund)"

  : "${GESUND_SELF_IMAGE:=travisci/gesund}"

  docker stop "${name}" &>/dev/null || true
  docker rm -f "${name}" &>/dev/null || true

  local env_file
  env_file="$(tfw writeenv gesund "${name}")"

  exec docker run \
    --rm \
    --name "${name}" \
    --env-file "${env_file}" \
    -p "${GESUND_PUBLISH_PORT:-80}":8192 \
    "${GESUND_SELF_IMAGE}"
}

main "$@"
